### PR TITLE
Updated `timeout` values; Add support for `$new(timeout=)`; Drop CI support for `$new(load_timeout=)`; Add option and envvar support for `$new(load_timeout=, timeout=)`

### LINKED ISSUE #213: Package option for `wait_for_*()` timeouts
If you're using a lot of `$wait_for_js()` calls, 30 seconds is a massively long timeout, and it'd be nice to be able to set a global option for the default timeout, e.g.

```r
options(shinytest2.wait_for_js.timeout = 5 * 1000)
```

instead of having to include `timeout = 5 * 1000` in all of my calls to `$wait_for_js()`. I would imagine heavy users of other `wait_for_*()` functions would benefit from similar options.

An alternative would be to lower the timeout for all of the wait functions to something reasonably small, e.g. 5 or 10 seconds, and then users who know they need to wait longer can opt into a longer wait time. (And I guess you'd also use longer timeouts for app startup.)

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #213

- [x] Tests
- [x] News entry

### CODE REVIEW

**Comment by schloerke** [comment]
I'm thinking we should scrap the timeout methods entirely and just make the startup time 10s and all other timeouts 4s. 

The timeout defaults could be `missing_arg()` or `getOption("shinytest2.timeout", 4 * 1000)`. If it is a `missing_arg()`, we could have it read the internal timeout value from `AppDriver$new(timeout = XYZ)`. If not a `missing_arg()`, then there's no need for `AppDriver$new(timeout = XYZ)`.

The `AppDriver$new(load_timeout=)` could default to `getOption("shinytest2.load_timeout", 10 * 1000)` instead of `NULL` to be explicit.

------------------------------

Then there's no confusion about CI... which value has been set... why the method name is about timeout, but arguments are about _step_ or _stepsize_ which doesn't immediately mean anything about timeouts.

Everything is just straight forward. Here's the timeout value.

**Comment by schloerke** [comment]
Original PR from `{shinytest}`: https://github.com/rstudio/shinytest/pull/335/files

I think the only motivation was for GHA to be able to load the shiny apps without having to set any parameters. I think I was wrong to take that motivation for all timeout values within the package

**Comment by schloerke** [comment]
Moving forward with something like
```r
# Definition could be
app1 <- AppDriver$new(
  load_timeout = getOption("shinytest2.load_timeout", 10 * 1000),
  timeout = getOption("shinytest2.timeout", 4 * 1000)
)
# Definition could be
app1$run_js(timeout = missing_arg())
```

-------------------

- [ ] Implement new approach

**Comment by gadenbuie** [comment]
> I think the only motivation was for GHA to be able to load the shiny apps without having to set any parameters.

For this motivation it might be worth adding an envvar lookup to the default value resolution, e.g. options → envvar → default value, since it's a lot easier to set the envvar in CI.

**Review by gadenbuie — APPROVED** [review]
Looks great! ⏲️ ⏳

**Pull request merged**
