### PR TITLE
v0.1.1

### PR DESCRIPTION
**Pull request by schloerke**
Update docs for CRAN

-----------------------------

- [x] Make PR from latest tag version
- [x] Update docs
- [x] Add NEWS entry
- [x] Submit `devtools::check_win_devel()`
- [x] Pass `devtools::check_win_devel()`
- [x] Reviewer approval
- [x] Submit to CRAN
- [x] CRAN accepts
- [x] Tag / Release from PR directly
- [x] Merge changes from `main`
- [ ] Merge PR

### CODE REVIEW

**Comment by schloerke** [comment]
Can't merge from main until after accepted on CRAN

**Review by wch — APPROVED** [review]

**Comment by schloerke** [comment]
🤞 Submitted

**Comment by schloerke** [comment]
CRAN accepted in 10 minutes!

**Comment by schloerke** [comment]
Release made: https://github.com/rstudio/shinytest2/releases/tag/v0.1.1
Merging in `main` to squash merge changes back into `main`

**Pull request merged**
